hbp:
  hasura:
    enabled: false
    serviceName: hasura
  minio:
    enabled: false
  storage:
    enabled: false
  enabled: true
  ingress:
    enabled: true
traefik:
  enabled: false
hasura:
  imageConfig:
    repository: platyplus/hasura-vue
    tag: latest
  enabled: true
  ingress:
    enabled: true
vue:
  enabled: true
  ingress:
    enabled: true
  imageConfig:
    repository: platyplus/incubator-vue
    tag: latest
  configFile:
    enabled: true
    values:
      ? HBP_ENDPOINT
      ? HASURA_ENDPOINT
