{{- if .Values.dns.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt
spec:
  secretName: acme-crt-secret
  dnsNames:
{{- range .Values.dns.domains }}
    - {{ . | quote}}
    - {{ printf "*.%s" . | quote }}
{{- end }}
  issuerRef:
    name: {{ printf "letsencrypt-%s" .Values.environment }}
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}