apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: {{ .Values.email }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: issuer-account-key-staging
    solvers:
      - http01:
          ingress:
            class: traefik-cert-manager  
    {{- if .Values.dns.enabled }}
      - dns01:
    {{- if eq .Values.dns.type "digitalocean" }}
          digitalocean:
            tokenSecretRef:
              name: {{ .Chart.Name }}-secrets
              key: digitalocean.token
        selector:
          dnsNames:
          {{- range .Values.dns.domains }}
            - {{ . | quote}}
            - {{ printf "*.%s" . | quote }}
          {{- end }}
    {{- end }}
    {{- end }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: {{ .Values.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: issuer-account-key 
    solvers:
      - http01:
          ingress:
            class: traefik-cert-manager  
    {{- if .Values.dns.enabled }}
      - dns01:
    {{- if eq .Values.dns.type "digitalocean" }}
          digitalocean:
            tokenSecretRef:
              name: {{ .Chart.Name }}-secrets
              key: digitalocean.token
        selector:
          dnsNames:
          {{- range .Values.dns.domains }}
            - {{ . | quote}}
            - {{ printf "*.%s" . | quote }}
          {{- end }}
    {{- end }}
    {{- end }}
