---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
{{- if .Values.dns.enabled }}
{{- if eq .Values.dns.type "digitalocean" }}
  digitalocean.token: {{ .Values.dns.token | b64enc | quote }}
{{- end }}
{{- end }}
