apiVersion: v2
description: a dummy project
name: dummy
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: standard-service
    repository: file://../../charts/standard-service
    version: "*"
    alias: web
    condition: web.enabled
  - name: standard-service
    alias: node
    version: "*"
    repository: file://../../charts/standard-service
    condition: node.enabled
  - name: hasura
    alias: hasura
    version: "*"
    repository: file://../../charts/hasura
    condition: hasura.enabled
  - name: traefik
    version: v8.9.1
    repository: https://containous.github.io/traefik-helm-chart
    condition: traefik.enabled
