traefik:
  enabled: false
hbp:
  connect:
    hasura:
      enabled: true
  enabled: true
node:
  targetPort: 3000
  imageConfig:
    tag: latest
    pullPolicy: IfNotPresent
  enabled: true
  ingress:
    enabled: true
web:
  targetPort: 8080
  imageConfig:
    tag: latest
    pullPolicy: IfNotPresent
  enabled: true
  ingress:
    enabled: true
hasura:
  enabled: true
  ingress:
    enabled: true
