services:
  # TODO is this really usefull as it can be inferred when platyplus is present in package.json?
  # TODO in a way, yes as it can activate/deactivate services. But it could also be an option in package.json...
  - package: '@platyplus/node-dummy'
# skaffold:
#   apiVersion: skaffold/v2beta7
#   kind: Config
#   build:
#     artifacts:
#       - image: hello-world
#         context: ..
#         docker:
#           buildArgs:
#             SERVICE: dummy/node

#   deploy:
#     helm:
#       releases:
#         - name: hello-world
#           chartPath: node/charts
#           artifactOverrides:
#             image: hello-world

#   profiles:
#     - name: dev
#       activation:
#         - command: dev
#       ## TODO deploy and port-forward traefik
#       build:
#         artifacts:
#           - image: hello-world
#             context: ..
#             docker:
#               dockerfile: Dockerfile-development
#               buildArgs:
#                 SERVICE: 'dummy/node'
#             sync:
#               manual:
#                 # Sync all the javascript files that are in the src folder
#                 # with the container src folder
#                 - src: "dummy/node/src/**/*.ts"
#                   dest: .
