apiVersion: skaffold/v2beta8
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: dummy-node
      context: ..
      docker:
        dockerfile: dummy/node/Dockerfile
    - image: dummy-web
      context: ..
      docker:
        dockerfile: dummy/web/Dockerfile
    - image: dummy-hasura
      context: hasura
deploy:
  helm:
    releases:
      - name: dummy
        chartPath: helm
        skipBuildDependencies: false
        artifactOverrides:
          node:
            image: dummy-node
          web:
            image: dummy-web
          hasura:
            image: dummy-hasura
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: dummy-node
          context: ..
          docker:
            dockerfile: dummy/node/Dockerfile-development
          sync:
            manual:
              - src: dummy/node/src/**/*.{ts,json}
                dest: .
        - image: dummy-web
          context: ..
          docker:
            dockerfile: dummy/web/Dockerfile-development
          sync:
            manual:
              - src: dummy/web/public/**/*
                dest: .
        - image: dummy-hasura
          context: hasura
          sync:
            manual:
              - src: migrations/**/*
                dest: .
              - src: metadata/*
                dest: .
            infer: null
      tagPolicy:
        sha256: {}
    deploy:
      helm:
        releases:
          - name: dummy
            chartPath: helm
            skipBuildDependencies: false
            artifactOverrides:
              node:
                image: dummy-node
              web:
                image: dummy-web
              hasura:
                image: dummy-hasura
            setValues:
              hasura:
                postgresql:
                  postgresqlPassword: development-postgres-password
                adminSecret: development-hasura-admin-secret
                jwt:
                  key: long-hasura-jwt-more-than-thirty-two-characters
                  algorithm: HS256
              traefik:
                enabled: true
              global:
                ingress:
                  enabled: true
                  domain: localhost
              web:
                targetPort: 8080
