# TODO reproduce in pdt
# TODO expose ports / use traeffik/ingress
# ? create a 'traefik' helm release in the dev profile?
apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
    - image: dummy-node
      context: ..
      docker:
        dockerfile: dummy/node/Dockerfile
    - image: dummy-web
      context: ..
      docker:
        dockerfile: dummy/web/Dockerfile
deploy:
  helm:
    releases:
      - name: dummy
        chartPath: helm
        # namespace: skaffold
        skipBuildDependencies: true
        setValues:
          web.ingress.enabled: false # TODO move to the dev profile
        artifactOverrides:
          web:
            image: dummy-web
          node:
            image: dummy-node
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: dummy-node
          context: ..
          docker:
            dockerfile: dummy/node/Dockerfile-development 
          sync:
            manual:
              - src: dummy/node/src/**/*.{ts,json}
                dest: .
        - image: dummy-web
          context: ..
          docker:
            dockerfile: dummy/web/Dockerfile-development
          sync:
            manual:
              - src: dummy/web/src/**/*.{ts,vue,json,sass,html}
                dest: .
              - src: dummy/web/quasar.conf.js
                dest: .
              - src: dummy/web/src/assets/**/*
                dest: .
              - src: dummy/web/public/**/*
                dest: .
