apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts: []
deploy:
  helm:
    releases:
      - name: /Users/pilou/dropbox/dev/platyplus/monorepo/dummy
        chartPath: helm
profiles:
  - name: dev
    activation:
      - command: dev
