traefik:
  enabled: true
hasura:
  imageConfig:
    repository: hasura
  ingress:
    hosts:
      - name: hasura.localhost
    enabled: true
  postgresql:
    postgresqlPassword: development-postgres-password
  adminSecret: development-hasura-admin-secret
  jwt:
    key: long-hasura-jwt-more-than-thirty-two-characters
    algorithm: HS256
frontend:
  ingress:
    hosts:
      - name: www.localhost
  targetPort: 8080
  configFile:
    path: /home/node/app/platyplus/frontend/public
    values:
      HASURA_ENDPOINT: http://hasura.localhost
      HBP_ENDPOINT: http://hbp.localhost
hbp:
  imageConfig:
    repository: hbp
  ingress:
    enabled: true
    hosts:
      - name: hbp.localhost
    