traefik:
  enabled: false
hasura-backend-plus:
  enabled: true
  imageConfig:
    tag: latest
    pullPolicy: IfNotPresent
  connect:
    hasura:
      enabled: true
  serverUrl: web.{{ .Values.global.ingress.domain }}
  minio:
    enabled: true
    defaultBuckets: tilehuria
    accessKey:
      password: minio-access-key
    secretKey:
      password: minio-secret-key
  ingress:
    enabled: true
hasura:
  enabled: true
  imageConfig:
    repository: platyplus/tilehuria-hasura
    tag: latest
    pullPolicy: IfNotPresent
  extraEnv:
    - name: HOOKS_URL
      value: http://{{ .Release.Name }}-hooks
    - name: EVENT_AOI
      value: http://{{ .Release.Name }}-hooks:3000/events/area-of-interest
    - name: EVENT_TILE_SET
      value: http://{{ .Release.Name }}-hooks:3000/events/tile-set
  ingress:
    enabled: true
web:
  imageConfig:
    tag: latest
    pullPolicy: IfNotPresent
  enabled: true
  ingress:
    enabled: true
rabbitmq:
  enabled: true
hooks:
  targetPort: 3000
  imageConfig:
    tag: latest
    pullPolicy: IfNotPresent
  enabled: true
  connect:
    hasura:
      enabled: true
    rabbitmq:
      enabled: true
worker:
  targetPort: 3000
  imageConfig:
    tag: latest
    pullPolicy: IfNotPresent
  enabled: true
  connect:
    hasura:
      enabled: true
    rabbitmq:
      enabled: true
    minio:
      enabled: true
