hasura-backend-plus:
  storage:
    enabled: false
  minio:
    enabled: false
  hasura:
    imageConfig:
      repository: platyplus/hasura
      tag: latest

frontend:
  enabled: true
  imageConfig:
    repository: platyplus/platyplus
    tag: latest
  # configFile:
  #   enabled: true
  #   values:
  #     hasuraUrl: http://hasura.test.com
  #     authUrl: http://hbp.test.com
