apiVersion: skaffold/v2beta8
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: hasura
      context: hasura
    - image: frontend
      context: ..
      docker:
        dockerfile: platyplus/frontend/Dockerfile
    - image: hbp
      context: hbp
deploy:
  helm:
    releases:
      - name: platyplus
        chartPath: helm
        skipBuildDependencies: false
        artifactOverrides:
          hasura:
            image: hasura
          frontend:
            image: frontend
          hbp:
            image: hbp
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      tagPolicy:
        sha256: {}
      artifacts:
        - image: hasura
          context: hasura
          sync:
            manual:
              - src: migrations/**/*
                dest: /hasura-migrations
              - src: metadata/*
                dest: /hasura-metadata
        - image: frontend
          context: ..
          docker:
            dockerfile: platyplus/frontend/Dockerfile-development
          sync:
            manual:
              - src: packages/vue-hasura-backend-plus/src/**/*
                dest: .
              - src: packages/rxdb-hasura/src/**/*
                dest: .
              - src: packages/vue-rxdb-hasura/src/**/*
                dest: .
              - src: platyplus/frontend/src/**/*
                dest: .
    deploy:
      helm:
        releases:
          - name: platyplus
            chartPath: helm
            skipBuildDependencies: false
            setValues:
              traefik:
                enabled: true
              hasura:
                ingress:
                  "hosts[0].name": hasura.localhost
                  enabled: true
                postgresql:
                  postgresqlPassword: development-postgres-password
                adminSecret: development-hasura-admin-secret
                jwt:
                  key: long-hasura-jwt-more-than-thirty-two-characters
                  algorithm: HS256
              frontend:
                ingress:
                  "hosts[0].name": www.localhost
                targetPort: 8080
                configFile:
                  path: /home/node/app/platyplus/frontend/public
                  values:
                    HASURA_ENDPOINT: http://hasura.localhost
                    HBP_ENDPOINT: http://hbp.localhost
              hbp:
                ingress:
                  "hosts[0].name": hbp.localhost
                  enabled: true
            artifactOverrides:
              hasura:
                image: hasura
              frontend:
                image: frontend
