apiVersion: v2
name: hasura-backend-plus
description: Hasura Backend Plus
home: https://platy.dev/charts/hasura-backend-plus.html
sources:
  - https://github.com/platyplus/platydev/tree/master/charts/hasura-backend-plus
  - https://github.com/nhost/hasura-backend-plus
icon: https://nhost.github.io/hasura-backend-plus/img/logo.png
appVersion: 2.7.1
version: 0.1.13
dependencies:
  - name: minio
    version: 8.0.1
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
  - name: hasura
    version: 0.1.8
    repository: file://../hasura
    condition: hasura.enabled
  - name: common
    version: 1.9.0
    repository: https://charts.bitnami.com/bitnami
keywords:
  - hasura-backend-plus
  - hasura
  - graphql
  - postgresql
  - minio
  - authentication
  - storage
