{{- $jwtSecret := include "hasura-backend-plus.jwtSecret" . -}}
{{- $adminSecret := include "hasura-backend-plus.adminSecret" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hasura-backend-plus.fullname" . }}
type: Opaque
data:
  cookies.secret: {{ (include "hasura-backend-plus.cookiesSecret" .) | b64enc | quote }}
  adminSecret: {{ $adminSecret | b64enc | quote }}
  jwt.secret: {{ $jwtSecret | b64enc | quote }}
  jwt.key: {{ (fromJson $jwtSecret).key | b64enc | quote }}

{{- if .Values.auth.providers.github.enabled }}
  github.client-secret: {{ .Values.auth.providers.github.clientSecret | b64enc | quote }}
{{- end }}
{{- if .Values.auth.providers.google.enabled }}
  google.client-secret: {{ .Values.auth.providers.google.clientSecret | b64enc | quote }}
{{- end }}
{{- if .Values.auth.providers.facebook.enabled }}
  facebook.client-secret: {{ .Values.auth.providers.facebook.clientSecret | b64enc | quote }}
{{- end }}
{{- if .Values.auth.providers.linkedin.enabled }}
  linkedin.client-secret: {{ .Values.auth.providers.linkedin.clientSecret | b64enc | quote }}
{{- end }}
{{- if .Values.auth.providers.windowsLive.enabled }}
  windows-live.client-secret: {{ .Values.auth.providers.windowsLive.clientSecret | b64enc | quote }}
{{- end }}
{{- if .Values.auth.providers.twitter.enabled }}
  twitter.consumer-secret: {{ .Values.auth.providers.twitter.consumerSecret | b64enc | quote }}
{{- end }}
{{- if .Values.auth.providers.apple.enabled }}
  apple.key-id: {{ .Values.auth.providers.apple.keyId | b64enc | quote }}
  apple.private-key: {{ .Values.auth.providers.apple.privateKey | b64enc | quote }}
{{- end }}
{{- if .Values.storage.external.enabled }}
  s3.access-key: {{ .Values.storage.external.accessKey | b64enc | quote }}
  s3.secret-key: {{ .Values.storage.external.secretKey | b64enc | quote }}
{{- end }}
{{- if .Values.emails.enabled }}
  emails.smtp.password: {{ .Values.emails.smtp.password | b64enc | quote }}  
{{- end }}
