name: build docker images
on:
  push:
    branches:
      - master
jobs:
  nx:
    name: Nx build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: lint,build:production
          all: 'true'
          nxCloud: 'true'
