name: build docker images
on:
  push:
    branches:
      - master
jobs:
  nx:
    name: Nx build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install packages
        run: yarn
      - uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: lint,build:production
          all: 'true'
          nxCloud: 'true'
