name: Latest commit on master
on:
  push:
    branches:
      - master # TODO filter pushes with tags - handled in another workflow
jobs:
  nx:
    name: Nx lint,build,deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install NodeJS packages
        run: yarn
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run Nx
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: lint,build:production,deploy
          projects: hasura,platyplus
          nxCloud: 'true'
