name: Latest commit on master
on:
  push:
    branches:
      - master # TODO filter pushes with tags - handled in another workflow
jobs:
  nx:
    name: Nx lint,build,deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install Helm & Push plugin
        run: |
          sudo snap install helm --classic
          helm plugin install https://github.com/chartmuseum/helm-push.git
          helm repo add platydev https://charts.platy.dev --username "$CHARTMUSEUM_USER" --password "$CHARTMUSEUM_PASSWORD"
        env:
          CHARTMUSEUM_USER: ${{ secrets.CHARTMUSEUM_USER }}
          CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install NodeJS packages
        run: yarn
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Lint
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: lint
          projects: platyplus
          nxCloud: 'true'
      - name: Build
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: build
          projects: hasura,platyplus
          nxCloud: 'true'
          args: --configuration=production
      - name: Deploy
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: deploy
          projects: hasura,platyplus,charts-hasura,charts-hasura-backend-plus,charts-standard-service
          nxCloud: 'true'
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
