name: Publish artifacts on tag
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
jobs:
  nx:
    name: Nx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install Helm & Push plugin
        run: |
          sudo snap install helm --classic
          helm plugin install https://github.com/chartmuseum/helm-push.git
          helm repo add platydev https://charts.platy.dev --username "$CHARTMUSEUM_USER" --password "$CHARTMUSEUM_PASSWORD"
        env:
          CHARTMUSEUM_USER: ${{ secrets.CHARTMUSEUM_USER }}
          CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install NodeJS packages
        run: yarn
      - name: Lint
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: lint
          all: 'true'
          parallel: 'true'
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: publish
          all: 'true'
          # TODO Check version before publish so it avoids to try to publish already existing version.
          # * done: NPM
          # TODO  : Docker, Helm Charts?
          # TODO -----------------------------------------------------------
          # TODO ----> OR: pass on 'projects' through the git tags???? <----
          # TODO -----------------------------------------------------------
          nxCloud: 'true'
